export const env = {
  appName: Bun.env.APP_NAME ?? 'MyApp',
  appDebug: Bun.env.APP_DEBUG === 'true',
  serverPort: Number(Bun.env.SERVER_PORT ?? 3000),
  dbConectionString: Bun.env.DB_CONNECTION_STRING ?? 'mongodb://localhost:27017',
  dbName: Bun.env.DB_NAME ?? 'sample_mflix',
  workerId: Number(Bun.env.WORKER_ID ?? 0),
  workerCpus: Number(Bun.env.WORKER_CPUS ?? 1),
  workerTag: [
    '[⚫ w:00]',
    '[🔵 w:01]',
    '[🟢 w:02]',
    '[🟡 w:03]',
    '[🔴 w:04]',
    '[🟣 w:05]',
    '[🟠 w:06]',
    '[⚪ w:07]',
    '[🟤 w:08]',
    '[🟦 w:09]',
    '[🟩 w:10]',
    '[🟨 w:11]',
    '[🟥 w:12]',
    '[🟪 w:13]',
    '[🟧 w:14]',
    '[⬜ w:15]',
    '[🟫 w:16]',
  ][Number(Bun.env.WORKER_ID ?? 0)],
}
